<a href="https://colab.research.google.com/github/varshith1038/assigments/blob/main/ML_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
#1. Creating an array
arr1= np.array([0,1,2,3,4,5,6,7,8,9])
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#2. Square of each element in array
arr2=arr1**2
print(arr2)


[ 0  1  4  9 16 25 36 49 64 81]


In [6]:
#3. Transformation
arr3=arr1.reshape(2,5)
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
#4. Slice of Life
arr4 = arr1[3:6]
print(arr4)
#We can refer slicing in data analysis as deep investigation and effeicient results

[3 4 5]


In [8]:
#5. Conditional
mask = arr1>5
arr5 = arr1[mask]
print(arr5)

[6 7 8 9]


In [9]:
#6. Mean , Median and Standard Deviation
arr6 = np.array([np.mean(arr1), np.median(arr1), np.std(arr1)])
print(arr6)

[4.5        4.5        2.87228132]


In [10]:
#7. Matrix product
array1 = np.array([[1,2], [3,4]])
array2 = np.array([[4,5], [1,1]])

arr7 = np.matmul(array1,array2)
print(arr7)

[[ 6  7]
 [16 19]]


In [15]:
#8. Odd one out

arr8 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


mask = arr8 % 2 != 0
arr8[mask] = -1

print(arr8)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [16]:
#9. Random generation 3x3 Matrices
arr9 = np.random.randint(1,50, size=(3,3))
print(arr9)

[[ 9 12  6]
 [39 37 23]
 [48  5 31]]


In [22]:
#10. Joining or Concatination
arr10_Vertical = np.concatenate((array1,array2), axis = 0)
arr10_Horizontal = np.concatenate((array1, array2), axis = 1)
print("Vertical\n", arr10_Vertical)
print("Horizontal\n",arr10_Horizontal)

Vertical
 [[1 2]
 [3 4]
 [4 5]
 [1 1]]
Horizontal
 [[1 2 4 5]
 [3 4 1 1]]


In [24]:
#11. Intersection of two arrays
arr11 = np.intersect1d(array1,array2)
print(arr11)

[1 4]


In [ ]:
#12. CSV file in to array format
Data = np.genfromtxt('train.csv', delimiter=',')
#print(Data)
first_column = data[:, 0]
print(first_column)

In [35]:
#13. Complex number handling
complex_array = np.array([2 + 3j, 1 - 1j, 5 + 2j, 3 - 4j])
sorted_array = np.sort_complex(complex_array)
print(complex_array)
print(sorted_array)

[2.+3.j 1.-1.j 5.+2.j 3.-4.j]
[1.-1.j 2.+3.j 3.-4.j 5.+2.j]


In [39]:
#14. Solving linear equations
A = np.array([[2, 3],
              [4, -1]])

B = np.array([12, 5])

X = np.linalg.solve(A, B)

print("x =", X[0])
print("y =", X[1])

x = 1.9285714285714286
y = 2.7142857142857144
